### ISSUE TITLE
Cores are marked as renewable even after the PotentialRenewal has expired

### ISSUE THREAD

**Issue by seadanda** [RegionX-Labs/CoretimeHub#248]
If a core is renewable in sale n, but the core is not renewed, it is still shown as renewable in subsequent sales.

Presumably this can be solved by checking the `PotentialRenewal` timeslice in state to see if it has passed.

This was the case this sale period on core 56 for para id 2048, despite the renewal having been missed.

**Comment by Szegoo** [comment]
Thanks for reporting, will resolve. It might also be worth considering for the Coretime chain to automatically clear up expired potential renewals.
